export const ROUTE_NAME = {
  MODAL: "modal",
  EXPLORE: "explore",
  SIGN_IN: "sign-in",
  TABS: "(tabs)",
  LIBRARY: "library",
  AGENDA: "agenda",
  PROFILE: "profile",
  TIPS: "tips",
  ARTICLES: "articles",
  SIGN_UP: "sign-up",
  FORGOT_PASSWORD: "forgot-password",
  PASSWORD_RESET_SENT: "password-reset-sent",
  RESET_PASSWORD: "reset-password",
  PASSWORD_CHANGED: "password-changed",
  LANDING: "landing",
  ONBOARDING: "onboarding",
  VERIFY_EMAIL: "verify-email",
  EMAIL_VERIFIED: "email-verified",
  COMPLETE_PROFILE: "complete-profile",
  PROFILE_COMPLETED: "profile-completed",
  WELLNESS: "wellness",
  VIEW_SORT_STATISTICS: "view-sort-statistics",
  EDIT_SORT_STATISTICS: "edit-sort-statistics",
  ACTIVITY_DISTRIBUTION: "activity-distribution",
  NUMBER_OF_STEPS: "number-of-steps",
  WEIGHT_TRACKING: "weight-tracking",
  TRAINING_VOLUME: "training-volume",
  ACTIVITY_TIME: "activity-time",
  EXERCISE_LIST: "exercise-list",
  EXERCISE_DETAIL: "exercise-detail",
  EXERCISE_FILTER: "exercise-filter",
  EXERCISE_FILTER_MUSCLES: "exercise-filter-muscles",
  EXERCISE_FILTER_SPORTS: "exercise-filter-sports",
  EXERCISE_FILTER_THEMES: "exercise-filter-themes",
  SESSION_VIEW: "session-view",
  PROGRAM_DETAIL: "program-detail",
  PROGRAM_DETAIL_ACTION: "program-detail-action",
  BUY_EXERCISE: "buy-exercise",
  PAYMENT_CONFIRMED: "payment-confirmed",
  CREATE_SESSION: "create-session",
  EDIT_SESSION: "edit-session",
  ADD_BLOCK: "add-block",
  SUBSCRIPTION: "subscription",
  SUBSCRIPTION_CHECKOUT: "subscription-checkout",
  SESSION_VIEW_PERSONAL: "session-view-personal",
  SESSION_VIEW_INDIVIDUALIZED: "session-view-individualized",
  NOTE_HISTORY: "note-history",
  MODIFY_TIMER: "modify-timer",
  TIMER_EXPANDED: "timer-expanded",
  SESSION_ENDED_FORM: "session-ended-form",
  SESSION_EVALUATION: "session-evaluation",
  MY_COACH: "my-coach",
  MESSAGING: "messaging",
  NOTIFICATIONS: "notifications",
  SETTINGS: "settings",
  EDIT_PROFILE: "edit-profile",
  CONFIGURE_FEELING: "configure-feeling",
  CONFIGURE_SHAPE_TRACKING: "configure-shape-tracking",
  CHOOSE_UNIT: "choose-unit",
  APP_LANGUAGE: "app-language",
  CONTACT_SUPPORT: "contact-support",
  TERM_OF_USE: "term-of-use",
  PRIVACY_POLICY: "privacy-policy",
  CHANGE_PASSWORD: "change-password",
  INJURIES: "injuries",
  ADD_INJURY: "add-injury",
  EDIT_INJURY: "edit-injury",
  EDIT_INJURY_AREA: "edit-injury-area",
  INJURY_VIEW: "injury-view",
  PHYSIOLOGICAL_DATA: "physiological-data",
  MY_SPORTS: "my-sports",
  MODIFY_MY_SPORTS: "modify-my-sports",
  SPORT_DETAIL: "sport-detail",
  ADD_SPORT_OBJECTIVE: "add-sport-objective",
  MODIFY_SPORT_OBJECTIVE: "modify-sport-objective",
  MY_RECORDS: "my-records",
  RECORD_DETAIL: "record-detail",
  RECORD_DETAIL_ITEM: "record-detail-item",
  ADD_RECORD: "add-record",
} as const;

/**
 * type-safe route constants to be used on the app
 */
export const ROUTE = {
  ROOT: "/" as const,
  SIGN_IN: `/${ROUTE_NAME.SIGN_IN}` as const,
  TABS: `/${ROUTE_NAME.TABS}` as const,
  MODAL: `/${ROUTE_NAME.MODAL}` as const,
  EXPLORE: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.EXPLORE}` as const,
  LIBRARY: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.LIBRARY}` as const,
  AGENDA: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.AGENDA}` as const,
  PROFILE: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.PROFILE}` as const,
  TIPS: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.TIPS}` as const,
  ARTICLES: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.ARTICLES}` as const,
  SIGN_UP: `/${ROUTE_NAME.SIGN_UP}` as const,
  FORGOT_PASSWORD: `/${ROUTE_NAME.FORGOT_PASSWORD}` as const,
  PASSWORD_RESET_SENT: `/${ROUTE_NAME.PASSWORD_RESET_SENT}` as const,
  RESET_PASSWORD: `/${ROUTE_NAME.RESET_PASSWORD}` as const,
  PASSWORD_CHANGED: `/${ROUTE_NAME.PASSWORD_CHANGED}` as const,
  LANDING: `/${ROUTE_NAME.LANDING}` as const,
  ONBOARDING: `/${ROUTE_NAME.ONBOARDING}` as const,
  VERIFY_EMAIL: `/${ROUTE_NAME.VERIFY_EMAIL}` as const,
  EMAIL_VERIFIED: `/${ROUTE_NAME.EMAIL_VERIFIED}` as const,
  COMPLETE_PROFILE: `/${ROUTE_NAME.COMPLETE_PROFILE}` as const,
  PROFILE_COMPLETED: `/${ROUTE_NAME.PROFILE_COMPLETED}` as const,
  WELLNESS: `/${ROUTE_NAME.WELLNESS}` as const,
  VIEW_SORT_STATISTICS: `/${ROUTE_NAME.VIEW_SORT_STATISTICS}` as const,
  EDIT_SORT_STATISTICS: `/${ROUTE_NAME.EDIT_SORT_STATISTICS}` as const,
  ACTIVITY_DISTRIBUTION: `/${ROUTE_NAME.ACTIVITY_DISTRIBUTION}` as const,
  NUMBER_OF_STEPS: `/${ROUTE_NAME.NUMBER_OF_STEPS}` as const,
  WEIGHT_TRACKING: `/${ROUTE_NAME.WEIGHT_TRACKING}` as const,
  TRAINING_VOLUME: `/${ROUTE_NAME.TRAINING_VOLUME}` as const,
  ACTIVITY_TIME: `/${ROUTE_NAME.ACTIVITY_TIME}` as const,
  EXERCISE_LIST: `/${ROUTE_NAME.EXERCISE_LIST}` as const,
  EXERCISE_DETAIL: `/${ROUTE_NAME.EXERCISE_DETAIL}` as const,
  EXERCISE_FILTER: `/${ROUTE_NAME.EXERCISE_FILTER}` as const,
  EXERCISE_FILTER_MUSCLES: `/${ROUTE_NAME.EXERCISE_FILTER_MUSCLES}` as const,
  EXERCISE_FILTER_SPORTS: `/${ROUTE_NAME.EXERCISE_FILTER_SPORTS}` as const,
  EXERCISE_FILTER_THEMES: `/${ROUTE_NAME.EXERCISE_FILTER_THEMES}` as const,
  SESSION_VIEW: `/${ROUTE_NAME.SESSION_VIEW}` as const,
  PROGRAM_DETAIL: `/${ROUTE_NAME.PROGRAM_DETAIL}` as const,
  PROGRAM_DETAIL_ACTION: `/${ROUTE_NAME.PROGRAM_DETAIL_ACTION}` as const,
  BUY_EXERCISE: `/${ROUTE_NAME.BUY_EXERCISE}` as const,
  PAYMENT_CONFIRMED: `/${ROUTE_NAME.PAYMENT_CONFIRMED}` as const,
  CREATE_SESSION: `/${ROUTE_NAME.CREATE_SESSION}` as const,
  EDIT_SESSION: `/${ROUTE_NAME.EDIT_SESSION}` as const,
  ADD_BLOCK: `/${ROUTE_NAME.ADD_BLOCK}` as const,
  SUBSCRIPTION: `/${ROUTE_NAME.SUBSCRIPTION}` as const,
  SUBSCRIPTION_CHECKOUT: `/${ROUTE_NAME.SUBSCRIPTION_CHECKOUT}` as const,
  SESSION_VIEW_PERSONAL: `/${ROUTE_NAME.SESSION_VIEW_PERSONAL}` as const,
  SESSION_VIEW_INDIVIDUALIZED:
    `/${ROUTE_NAME.SESSION_VIEW_INDIVIDUALIZED}` as const,
  NOTE_HISTORY: `/${ROUTE_NAME.NOTE_HISTORY}` as const,
  MODIFY_TIMER: `/${ROUTE_NAME.MODIFY_TIMER}` as const,
  TIMER_EXPANDED: `/${ROUTE_NAME.TIMER_EXPANDED}` as const,
  SESSION_ENDED_FORM: `/${ROUTE_NAME.SESSION_ENDED_FORM}` as const,
  SESSION_EVALUATION: `/${ROUTE_NAME.SESSION_EVALUATION}` as const,
  MY_COACH: `/${ROUTE_NAME.MY_COACH}` as const,
  MESSAGING: `/${ROUTE_NAME.MESSAGING}` as const,
  NOTIFICATIONS: `/${ROUTE_NAME.NOTIFICATIONS}` as const,
  SETTINGS: `/${ROUTE_NAME.SETTINGS}` as const,
  EDIT_PROFILE: `/${ROUTE_NAME.EDIT_PROFILE}` as const,
  CONFIGURE_FEELING: `/${ROUTE_NAME.CONFIGURE_FEELING}` as const,
  CONFIGURE_SHAPE_TRACKING: `/${ROUTE_NAME.CONFIGURE_SHAPE_TRACKING}` as const,
  CHOOSE_UNIT: `/${ROUTE_NAME.CHOOSE_UNIT}` as const,
  APP_LANGUAGE: `/${ROUTE_NAME.APP_LANGUAGE}` as const,
  CONTACT_SUPPORT: `/${ROUTE_NAME.CONTACT_SUPPORT}` as const,
  TERM_OF_USE: `/${ROUTE_NAME.TERM_OF_USE}` as const,
  PRIVACY_POLICY: `/${ROUTE_NAME.PRIVACY_POLICY}` as const,
  CHANGE_PASSWORD: `/${ROUTE_NAME.CHANGE_PASSWORD}` as const,
  INJURIES: `/${ROUTE_NAME.INJURIES}` as const,
  ADD_INJURY: `/${ROUTE_NAME.ADD_INJURY}` as const,
  EDIT_INJURY: `/${ROUTE_NAME.EDIT_INJURY}` as const,
  EDIT_INJURY_AREA: `/${ROUTE_NAME.EDIT_INJURY_AREA}` as const,
  INJURY_VIEW: `/${ROUTE_NAME.INJURY_VIEW}` as const,
  PHYSIOLOGICAL_DATA: `/${ROUTE_NAME.PHYSIOLOGICAL_DATA}` as const,
  MY_SPORTS: `/${ROUTE_NAME.MY_SPORTS}` as const,
  MODIFY_MY_SPORTS: `/${ROUTE_NAME.MODIFY_MY_SPORTS}` as const,
  SPORT_DETAIL: `/${ROUTE_NAME.SPORT_DETAIL}` as const,
  ADD_SPORT_OBJECTIVE: `/${ROUTE_NAME.ADD_SPORT_OBJECTIVE}` as const,
  MODIFY_SPORT_OBJECTIVE: `/${ROUTE_NAME.MODIFY_SPORT_OBJECTIVE}` as const,
  MY_RECORDS: `/${ROUTE_NAME.MY_RECORDS}` as const,
  RECORD_DETAIL: `/${ROUTE_NAME.RECORD_DETAIL}` as const,
  RECORD_DETAIL_ITEM: `/${ROUTE_NAME.RECORD_DETAIL_ITEM}` as const,
  ADD_RECORD: `/${ROUTE_NAME.ADD_RECORD}` as const,
} as const;
