export const ROUTE_NAME = {
  MODAL: "modal",
  EXPLORE: "explore",
  SIGN_IN: "sign-in",
  TABS: "(tabs)",
  PROFILE: "profile",
  TIPS: "tips",
  ARTICLES: "articles",
  SIGN_UP: "sign-up",
  FORGOT_PASSWORD: "forgot-password",
  PASSWORD_RESET_SENT: "password-reset-sent",
  RESET_PASSWORD: "reset-password",
  PASSWORD_CHANGED: "password-changed",
  LANDING: "landing",
  ONBOARDING: "onboarding",
  VERIFY_EMAIL: "verify-email",
  EMAIL_VERIFIED: "email-verified",
  COMPLETE_PROFILE_1: "complete-profile-1",
  COMPLETE_PROFILE_2: "complete-profile-2",
  COMPLETE_PROFILE_3: "complete-profile-3",
  COMPLETE_PROFILE_4: "complete-profile-4",
  COMPLETE_PROFILE_5: "complete-profile-5",
  PROFILE_COMPLETED: "profile-completed",
} as const;

/**
 * type-safe route constants to be used on the app
 */
export const ROUTE = {
  ROOT: "/" as const,
  SIGN_IN: `/${ROUTE_NAME.SIGN_IN}` as const,
  TABS: `/${ROUTE_NAME.TABS}` as const,
  MODAL: `/${ROUTE_NAME.MODAL}` as const,
  EXPLORE: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.EXPLORE}` as const,
  PROFILE: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.PROFILE}` as const,
  TIPS: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.TIPS}` as const,
  ARTICLES: `/${ROUTE_NAME.TABS}/${ROUTE_NAME.ARTICLES}` as const,
  SIGN_UP: `/${ROUTE_NAME.SIGN_UP}` as const,
  FORGOT_PASSWORD: `/${ROUTE_NAME.FORGOT_PASSWORD}` as const,
  PASSWORD_RESET_SENT: `/${ROUTE_NAME.PASSWORD_RESET_SENT}` as const,
  RESET_PASSWORD: `/${ROUTE_NAME.RESET_PASSWORD}` as const,
  PASSWORD_CHANGED: `/${ROUTE_NAME.PASSWORD_CHANGED}` as const,
  LANDING: `/${ROUTE_NAME.LANDING}` as const,
  ONBOARDING: `/${ROUTE_NAME.ONBOARDING}` as const,
  VERIFY_EMAIL: `/${ROUTE_NAME.VERIFY_EMAIL}` as const,
  EMAIL_VERIFIED: `/${ROUTE_NAME.EMAIL_VERIFIED}` as const,
  COMPLETE_PROFILE_1: `/${ROUTE_NAME.COMPLETE_PROFILE_1}` as const,
  COMPLETE_PROFILE_2: `/${ROUTE_NAME.COMPLETE_PROFILE_2}` as const,
  COMPLETE_PROFILE_3: `/${ROUTE_NAME.COMPLETE_PROFILE_3}` as const,
  COMPLETE_PROFILE_4: `/${ROUTE_NAME.COMPLETE_PROFILE_4}` as const,
  COMPLETE_PROFILE_5: `/${ROUTE_NAME.COMPLETE_PROFILE_5}` as const,
  PROFILE_COMPLETED: `/${ROUTE_NAME.PROFILE_COMPLETED}` as const,
} as const;
